package com.ftest.test;

import scala.util.parsing.json.JSON;

import java.util.Arrays;

public class test5 {
    public static void main(String[] args) {
        String code = "PTBZ738B\n" +
                "DRG7B297\n" +
                "MG5QJHSW\n" +
                "XW6HC5BR\n" +
                "XNKBH4PN\n" +
                "TZ2GN5NC\n" +
                "U9L84TCB\n" +
                "DX2MDMXA\n" +
                "FUF7SYBP\n" +
                "BCNV7XHQ\n" +
                "2MRZKU5U\n" +
                "PVMK2P6B\n" +
                "RK59LQDU\n" +
                "PP8YG2S5\n" +
                "93TJJQDR\n" +
                "BZZ7SDAG\n" +
                "VFFGRY8R\n" +
                "SAYYAVNH\n" +
                "PZH8CXKE\n" +
                "ZJC3LPWC\n" +
                "F56K26MF\n" +
                "UW8J3Y87\n" +
                "QW3ASCLY\n" +
                "NCAFQCSE\n" +
                "T66ZNDJT\n" +
                "U2X3B22S\n" +
                "MTZ5VH4J\n" +
                "LV75VMKW\n" +
                "L9J3GAVL\n" +
                "RSPUEEN3\n" +
                "XUZTM4S5\n" +
                "252QDEMD\n" +
                "DZ35Z2QX\n" +
                "2G8XRZ7E\n" +
                "LP3JHTXE\n" +
                "LS7JMRP7\n" +
                "X4MPCRU5\n" +
                "VYR7LV37\n" +
                "VF5HH8Y5\n" +
                "CX2TZFBZ\n" +
                "27AQDWMG\n" +
                "DEEK98LJ\n" +
                "GYDBC9CW\n" +
                "8STFCRD4\n" +
                "TX9BGP5A\n" +
                "G9U6AVZS\n" +
                "6YAU3XL4\n" +
                "DADP3XQQ\n" +
                "Q5XB98HK\n" +
                "SM6JHT3X\n" +
                "VMDSBWM7\n" +
                "SAX3SFSX\n" +
                "FTSDSBSV\n" +
                "R3RKFH8S\n" +
                "4RSZXQ3D\n" +
                "SFSQMCAD\n" +
                "6CZMAKCG\n" +
                "DMSPJ22V\n" +
                "88G686YT\n" +
                "3FCCYJBS\n" +
                "DZSYC8VS\n" +
                "B29SVLAB\n" +
                "QAG8WQZH\n" +
                "GFQKHUPU\n" +
                "X9CY3RAD\n" +
                "5S87CPSQ\n" +
                "WYYVGWAN\n" +
                "FSBER9MJ\n" +
                "6UYVFQ44\n" +
                "A9XQZXUF\n" +
                "V39VGCJG\n" +
                "3AJ294XK\n" +
                "49EEC7XJ\n" +
                "685WXSUE\n" +
                "RP62Z6JL\n" +
                "SRPSKFF3\n" +
                "DRTNKSFA\n" +
                "5YJWB6DE\n" +
                "8AWYC9GT\n" +
                "MFZNSHLQ\n" +
                "XPNCQVXX\n" +
                "ABA4JHVS\n" +
                "BVTJ9A5A\n" +
                "VHWPAQP3\n" +
                "V6GPQ6U4\n" +
                "K63LD2JE\n" +
                "G3MM6LK9\n" +
                "RPK5BRFT\n" +
                "NK4CKDUU\n" +
                "QD94TZRQ\n" +
                "AKBWUK82\n" +
                "LENYD266\n" +
                "WS4PE8V5\n" +
                "9HUBA2WP\n" +
                "2QKTNNHN\n" +
                "96W5W28C\n" +
                "2MDQTMA9\n" +
                "3BTBDSC3\n" +
                "R9QZDVMF\n" +
                "VQ3FP92K\n" +
                "YFQPZL9D\n" +
                "DWM64RZ3\n" +
                "NTLWCRU9\n" +
                "VKKQXT8W\n" +
                "K8XUTXN4\n" +
                "77BPWJS7\n" +
                "82UV4RNH\n" +
                "L9PM7MET\n" +
                "AUQSVSE9\n" +
                "XYCJS6SQ\n" +
                "X39WN2K7\n" +
                "UKD3MCMY\n" +
                "LKYFR6F8\n" +
                "N2U3L426\n" +
                "J9QP5G5D\n" +
                "VJE7Y8TN\n" +
                "DY67433L\n" +
                "ZRDRE8PL\n" +
                "J222HFJU\n" +
                "UGXTE85D\n" +
                "S3BX2Z9B\n" +
                "VQGFEWAK\n" +
                "FJ574BSC\n" +
                "2P2DEXBD\n" +
                "48RVKXYP\n" +
                "9Y5CNHTA\n" +
                "MGJGMDLN\n" +
                "EKDWT29P\n" +
                "R227CNK5\n" +
                "595WTLNT\n" +
                "8SCLA3Z8\n" +
                "PNR5UV9Z\n" +
                "9XLYSHD3\n" +
                "GEL6D7TM\n" +
                "3JFHRRFQ\n" +
                "5RKVFCVC\n" +
                "GYQXFPX5\n" +
                "N8SR467N\n" +
                "RUEKNGWB\n" +
                "MSGXU2DF\n" +
                "HYPBV9SX\n" +
                "FQWQAJ7Z\n" +
                "CEZLM4AW\n" +
                "YRC3PMG7\n" +
                "B47SBZXE\n" +
                "V7SWUCXK\n" +
                "967R68WM\n" +
                "VK7LJUKN\n" +
                "QW4PF98L\n" +
                "Q75Z82RN\n" +
                "3LXZ8RXX\n" +
                "9HZPU2WH\n" +
                "5YVA5E37\n" +
                "QF8J3TG4\n" +
                "24GG47FS\n" +
                "M3QEMRQ2\n" +
                "KDRBJZ3A\n" +
                "UXZJQ76D\n" +
                "FFWS3GM5\n" +
                "7K5AXDR4\n" +
                "2SCE3HWU\n" +
                "7SM8DQRZ\n" +
                "2PJA6TLR\n" +
                "BMJTJCKQ\n" +
                "9CMX7MH4\n" +
                "HFE7MDJC\n" +
                "DW7WWRAK\n" +
                "FJZ9D99U\n" +
                "3QY2WVBR\n" +
                "HJCJM6GL\n" +
                "L8CRBVFE\n" +
                "E32359C2\n" +
                "YPAP8X4J\n" +
                "UU8RSTEL\n" +
                "UFH7UZ2W\n" +
                "JAHCRJ53\n" +
                "3PAVUJ5D\n" +
                "3RQZG9VH\n" +
                "YAHMPAH4\n" +
                "RGTV7GLN\n" +
                "MT7FC4GR\n" +
                "5ZJRWJM3\n" +
                "J8JPGRDW\n" +
                "U3M9G7K6\n" +
                "HFXJVLZQ\n" +
                "AWWD59N4\n" +
                "5KJUM5Y3\n" +
                "NS2DBHFX\n" +
                "9PYUV2DX\n" +
                "DE3GDFY4\n" +
                "2C5YJCAW\n" +
                "B5LJHA4N\n" +
                "WAPHKF9F\n" +
                "WPQK53Y4\n" +
                "8U8Z8PPP\n" +
                "C7N3HGEN\n" +
                "H64J3NF8\n" +
                "GE2SEWME\n" +
                "2EQTB94K\n" +
                "JEU5JEKQ\n" +
                "R7UXD6HX\n" +
                "VA8QY2CW\n" +
                "V2UZGRCN\n" +
                "TTU27L8E\n" +
                "MNDPCC8A\n" +
                "R77ATK8J\n" +
                "AMFX35SK\n" +
                "7242WDWC\n" +
                "4XDKXN78\n" +
                "HBANGECH\n" +
                "H2JREAMN\n" +
                "AWD3B8GT\n" +
                "JB6Q5GBY\n" +
                "CP2MU9CK\n" +
                "NVY4TP4K\n" +
                "7848TRNT\n" +
                "X6ESMHZC\n" +
                "LZ5YSYSN\n" +
                "SAUDCKNY\n" +
                "5BGZHEV8\n" +
                "B8C5CVCC\n" +
                "JFJJT3R7\n" +
                "YBUEV6F6\n" +
                "RMM4H89K\n" +
                "RZSD2FQV\n" +
                "5GTQ882E\n" +
                "3BX77TSG\n" +
                "Y3N8JWQT\n" +
                "ZGDKVVPV\n" +
                "SRM5V9VY\n" +
                "KJ8QJLHA\n" +
                "9YB55G4F\n" +
                "P2UFP6WQ\n" +
                "8QWFA7CH\n" +
                "75W2JFZJ\n" +
                "JQXGE2B7\n" +
                "UWEZ7HJ4\n" +
                "A3E98S9N\n" +
                "N5SNUJZ5\n" +
                "E9VDWZKG\n" +
                "2WC2LSNK\n" +
                "QNGPM7Z5\n" +
                "HDN34SMC\n" +
                "G7W85RYX\n" +
                "3FCS73NW\n" +
                "BES7PQSP\n" +
                "ALT6TGXQ\n" +
                "XENFBVLU\n" +
                "CVDKVWLZ\n" +
                "AKU4NFD6\n" +
                "4XMW4BBU\n" +
                "R5KLST8D\n" +
                "FQ9BA3AV\n" +
                "3F2A6NF7\n" +
                "SMAA2DYN\n" +
                "2JSS4ULW\n" +
                "FRLX8X3T\n" +
                "5WK8UM5F\n" +
                "BUMPFPK6\n" +
                "HCMMNNJG\n" +
                "JR96EXRY\n" +
                "VMZES4RX\n" +
                "ANG2FQ22\n" +
                "4ARW7CCD\n" +
                "JGV4F5LP\n" +
                "L6HSHX9S\n" +
                "LJ9KHCH6\n" +
                "SDM2W6VV\n" +
                "B242CL3U\n" +
                "6V23ZSE9\n" +
                "YBH2TJCJ\n" +
                "AWSRJZQN\n" +
                "DFCH98XV\n" +
                "LLXBU5F6\n" +
                "8BTSY6MP\n" +
                "J8XK7CLW\n" +
                "D9SCDXEH\n" +
                "MH9M4MJV\n" +
                "FEUNNBHG\n" +
                "TCBAY4XP\n" +
                "AB2LZ5LY\n" +
                "VY8B9VQJ\n" +
                "G76RJ5DH\n" +
                "L6DCJJRJ\n" +
                "YQQWWU2D\n" +
                "AH4KDJG6\n" +
                "2VHDLHJG\n" +
                "5CUMZXST\n" +
                "XLYZZALC\n" +
                "WLBAT3PY\n" +
                "MA87TPPS\n" +
                "YG6438P4\n" +
                "FRXNW3JZ\n" +
                "RH4RBMLJ\n" +
                "8H4MJF3D\n" +
                "6C3QSBUY\n" +
                "UTF3PZ8E\n" +
                "BNUJU5DF\n" +
                "8KA6989A\n" +
                "Q9HJR3WN\n" +
                "NTFJZXA7\n" +
                "XNDZQ9F4\n" +
                "53725MBN\n" +
                "CYKAN4MS\n" +
                "D4SFYU9P\n" +
                "NC82DK7M\n" +
                "MYS8DQXL\n" +
                "97WU7D9H\n" +
                "AUKPV69G\n" +
                "WELZ7V6W\n" +
                "JDNNWQLC\n" +
                "TMDM7CNU\n" +
                "DH44ADCA\n" +
                "J2CNG48N\n" +
                "L9P68WB7\n" +
                "92K6V9A7\n" +
                "ASGDXFQB\n" +
                "E2JVK5HA\n" +
                "9JAVWGD2\n" +
                "QLSHM48P\n" +
                "AYYPNB2G\n" +
                "UR5TQ5PE\n" +
                "KA3BL3JT\n" +
                "5WTNPD8G\n" +
                "PW3RRYFC\n" +
                "K2S4BY4D\n" +
                "NLHZPJN6\n" +
                "48YYJZNN\n" +
                "LDC9UTYQ\n" +
                "79ZYFPKB\n" +
                "TH8E67JZ\n" +
                "MQXZAST2\n" +
                "PVVJVXWE\n" +
                "9RKYSNSJ\n" +
                "DJAR4ZPU\n" +
                "87CH3U5F\n" +
                "FX3UZ49E\n" +
                "LYDWEZSW\n" +
                "JSMDMPTV\n" +
                "LVLZM4QU\n" +
                "GNZFL4WL\n" +
                "647ALFK7\n" +
                "NMGEGDA3\n" +
                "EKGGCY52\n" +
                "7FLBAD2H\n" +
                "L8AEVY5S\n" +
                "CXN9EFD6\n" +
                "9MPEZEZR\n" +
                "9XTNTLKY\n" +
                "YELKN2TE\n" +
                "XRM73J28\n" +
                "55A88TL9\n" +
                "R5DANYTA\n" +
                "56VYQWX9\n" +
                "YN7TM5W7\n" +
                "LRRRJ9YR\n" +
                "V98GAXE4\n" +
                "HFYE6SP2\n" +
                "HR9KGXNB\n" +
                "LPWARNJP\n" +
                "DFFKAHWE\n" +
                "XKHHAAP4\n" +
                "HQRLQYRK\n" +
                "VUPA342X\n" +
                "E7UAWF69\n" +
                "YKGAH5P3\n" +
                "M5DTBU3L\n" +
                "RCVYGFTB\n" +
                "Z2AY3HFH\n" +
                "QFCV6NZX\n" +
                "GBQPC4L9\n" +
                "H4XZDNJG\n" +
                "HEXCPL9Q\n" +
                "LUFBFY9H\n" +
                "W8S5MCT2\n" +
                "U75N95P4\n" +
                "JLP3FZZ5\n" +
                "3ZHQ6ZEN\n" +
                "ZCNAJAYR\n" +
                "35XB6G7F\n" +
                "Q7T5Z6VJ\n" +
                "8GSZE2H8\n" +
                "6SCV6KB8\n" +
                "KTZ6V6VF\n" +
                "DQ3HPGN3\n" +
                "JZBFDAF7\n" +
                "NFWVKLA2\n" +
                "TY57UMCF\n" +
                "4PJ96PYJ\n" +
                "98WZGFPX\n" +
                "9775QKS5\n" +
                "8KHL7J7T\n" +
                "XG9UTRHV\n" +
                "L94LEBDL\n" +
                "B5ALRQBK\n" +
                "D7JB5EY7\n" +
                "6CAM8QS6\n" +
                "RUYV8BYH\n" +
                "S9APJAHM\n" +
                "6MKDJ8G2\n" +
                "H9ADZQAA\n" +
                "ZQS4ZEAG\n";
        String[] split = code.split("\n");
        Arrays.stream(split).forEach(
                it -> {
                    System.out.println("\'" + it + "\'" + ",");
                }
        );
        System.out.println(split.length);
    }
}
